title: Koh DY Portfolio
#logo: /assets/img/headshort_circle.png
description: Address<br>Singapore 730547<br><br>Email<br>kdingyuan@gmail.com<br><br>LinkedIn<br><a href="https://www.linkedin.com/in/kohdy/">www.linkedin.com/in/kohdy/</a>
#show_downloads: false
theme: jekyll-theme-minimal
