title: Koh DY Portfolio
#logo: /assets/img/headshort_circle.png
description: Address<br>Singapore 730547<br><br>Contact<br>+65 8218 2117<br><br>Email<br>kdingyuan@gmail.com<br><br>LinkedIn<br><a href="https://www.linkedin.com/in/kohdy/" target="_blank">www.linkedin.com/in/kohdy/</a><br><br>PDF Downloads<br><a href="./assets/files/KohDingYuan_Resume.pdf" target="_blank">Resume</a> | <a href="./assets/files/KohDingYuan_Testimonials.pdf" target="_blank">Testimonials</a>
#show_downloads: false
theme: jekyll-theme-minimal
