title: Koh DY Portfolio
#logo: /assets/img/headshort_circle.png
description: Address<br>Singapore 730547<br><br>Email<br>kdingyuan@gmail.com<br><br>LinkedIn<br><a href="https://www.linkedin.com/in/kohdy/" target="_blank">www.linkedin.com/in/kohdy/</a><br><br><a href="./assets/files/KohDingYuan_Resume.pdf" target="_blank">Download PDF Resume</a><br><br><a href="./assets/files/KohDingYuan_Testimonials.pdf" target="_blank">Download PDF Testimonials</a>
#show_downloads: false
theme: jekyll-theme-minimal
