title: Koh Ding Yuan
#logo: /assets/img/headshort_circle.png
description: Apt Blk 547 Woodlands Dr 16<br>Singapore 730547<br><br>+65 8218 2117<br>kdingyuan@gmail.com<br><br> <a href="https://www.linkedin.com/in/kohdy/" target="_blank">www.linkedin.com/in/kohdy/</a><br><br>PDF Downloads<br> <a href="./assets/files/KohDingYuan_Resume.pdf" target="_blank">Resume</a> | <a href="./assets/files/KohDingYuan_Testimonials.pdf" target="_blank">Testimonials</a><br><details><summary>QR Code</summary><img src="./assets/images/qr_code.png" alt="QR Code" /></details>
#show_downloads: false
theme: jekyll-theme-minimal
